# Site settings
title: Floyo Development
email: folkert.jongbloed@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I am a passionate Android Watchface developer dedicated to transforming your smartwatch experience with vibrant and imaginative designs. My creations are not just about telling time; they are about making a statement and adding a splash of color to your wrist. With a keen eye for detail and a love for innovation, I craft watchfaces that are both functional and visually stunning.
baseurl: /
url: "https://folkertjo.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
permalink: /:year/:title:output_ext
